name: Build Docker Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@master
      - name: Building Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          # 下方的name格式为：Docker Hub ID/自定义镜像名称
          name: pigeonpig/acgfaka
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
          platforms: linux/amd64,linux/arm64
